#!/bin/bash
# Apply the bootstrap stack. This creates real Azure resources (the plan/apply Entra ID applications,
# service principals, role assignments) and the Azure Blob Storage state backend. Review the plan output
# above before running this. --no-stack-generate reuses the stack generated by the plan step so what you
# reviewed is exactly what is applied. State is still local at this point.
set -euo pipefail

if [ -z "${REPO_FILES:-}" ]; then
  log_error "No cloned repository found. Complete the earlier steps first."
  exit 1
fi

export ARM_SUBSCRIPTION_ID="{{ .outputs.derive_azure.azure_subscription_id }}"
export ARM_TENANT_ID="{{ .outputs.derive_azure.azure_tenant_id }}"

# Ordering guard: enabled only after the plan step has completed.
PLAN_DONE="{{ .outputs.bootstrap_plan.plan_complete }}"

cd "$REPO_FILES/{{ .inputs.SubscriptionName }}/bootstrap"

log_info "Applying the bootstrap stack (plan: ${PLAN_DONE})..."
terragrunt run --all --non-interactive --provider-cache --no-stack-generate apply

echo "bootstrap_applied=true" >> "$RUNBOOK_OUTPUT"

log_info "Bootstrap apply complete in subscription {{ .outputs.derive_azure.azure_subscription_id }}."
