#!/usr/bin/env bash
#
# Regenerates the TerragruntScaleCatalogRef dropdown in each runbook that is present.
#
# The Runbooks app reads each <Inputs> block's YAML when the runbook is opened,
# before any step has run, so the list of selectable catalog versions has to be
# baked into runbook.mdx ahead of time -- a script running mid-runbook cannot
# add to it. Run this after cutting a terragrunt-scale-catalog release and
# commit the result.
#
# The "latest" option is always first and stays the default: it is resolved at
# run time by each runbook's resolve-catalog-ref.sh, so a stale list never stops
# anyone from getting the newest release.
#
# Usage: scripts/update-catalog-refs.sh [number-of-releases]   (default: 10)

set -euo pipefail

readonly CATALOG_URL="https://github.com/gruntwork-io/terragrunt-scale-catalog.git"
readonly MARKER="  - name: TerragruntScaleCatalogRef"
readonly END_MARKER="    x-section: Advanced"

count=${1:-10}
case $count in
  ''|*[!0-9]*) echo "ERROR: release count must be a number, got '${count}'" >&2; exit 1 ;;
esac

cd "$(dirname "$0")/.."

echo "Fetching the ${count} newest terragrunt-scale-catalog releases..."
tags=$(git ls-remote --tags --refs --sort=-v:refname "$CATALOG_URL" 'v*' 2>/dev/null \
  | sed 's#.*refs/tags/##' \
  | head -n "$count")

if [ -z "$tags" ]; then
  echo "ERROR: could not list tags from ${CATALOG_URL} (offline?)" >&2
  exit 1
fi

echo "$tags" | sed 's/^/  /'

# Build the replacement block. Keep the description free of quote characters:
# it lives in a single-quoted YAML scalar inside an MDX code fence, and escaping
# quotes there is what produced the literal \"latest\" default this replaces.
block=$(cat <<'HEAD'
  - name: TerragruntScaleCatalogRef
    type: enum
    description: Which terragrunt-scale-catalog version this bootstrap pins. Leave it on latest to use the newest release, resolved when the generate step runs. Pick a tag instead to pin one explicitly.
    # Regenerated by scripts/update-catalog-refs.sh -- do not hand-edit.
    options:
      - latest
HEAD
)
while IFS= read -r tag; do
  block="${block}
      - ${tag}"
done <<< "$tags"
block="${block}
    default: latest
    validations:
      - required
${END_MARKER}"

# BSD awk rejects newlines in -v assignments, so hand the block over as a file.
blockfile=$(mktemp)
trap 'rm -f "$blockfile"' EXIT
printf '%s\n' "$block" > "$blockfile"

changed=0
for mdx in */runbook.mdx; do
  if ! grep -qF "$MARKER" "$mdx"; then
    echo "ERROR: ${mdx} has no '${MARKER# }' variable -- fix the marker or the runbook" >&2
    exit 1
  fi

  tmp="${mdx}.tmp.$$"
  awk -v marker="$MARKER" -v end_marker="$END_MARKER" -v blockfile="$blockfile" '
    $0 == marker {
      while ((getline line < blockfile) > 0) print line
      close(blockfile)
      skipping = 1
      next
    }
    skipping && $0 == end_marker { skipping = 0; next }
    skipping { next }
    { print }
    END {
      if (skipping) {
        print "ERROR: unterminated variable block" > "/dev/stderr"
        exit 1
      }
    }
  ' "$mdx" > "$tmp"

  if cmp -s "$mdx" "$tmp"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$mdx"
    echo "updated ${mdx}"
    changed=$((changed + 1))
  fi
done

echo "Done: ${changed} runbook(s) updated."
