[tools]
terragrunt = "{{ .TerragruntVersion }}"
{{ if eq .IaCTool "terraform" -}}
terraform = "{{ .TerraformVersion }}"
{{- else -}}
opentofu = "{{ .OpenTofuVersion }}"
{{- end }}
gcloud = "{{ .GCloudVersion }}"
